### ISSUE TITLE
[Question] Is it at least as stable as the "official" component?

### ISSUE THREAD

**Issue by JeanCollas** [amay077/Xamarin.Forms.GoogleMaps#149]
I have few issues with the official component (an extension of it), when embedded in tabs, or for unknown reasons. 
I get some exceptions from nowhere, at some rare occasions and totally randomly.
I would just like to know if this fixes some of the issues and/or creates some. (mostly from the android component)

**Comment by deextercz** [comment]
Could you provide exception, stack trace, screenshot, steps to reproduce?

**Comment by JeanCollas** [comment]
That kind, but I have no idea how to reproduce
```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v4.app.FragmentManagerState
	at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
	at android.os.Parcel.readParcelable(Parcel.java:2358)
	at android.os.Parcel.readValue(Parcel.java:2264)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.Bundle.getBundle(Bundle.java:763)
	at aby.a(:com.google.android.gms.DynamiteModulesB:74)
	at maps.ad.t.a(Unknown Source)
	at maps.ad.R.a(Unknown Source)
	at xx.onTransact(:com.google.android.gms.DynamiteModulesB:66)
	at android.os.Binder.transact(Binder.java:387)
	at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
	at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
	at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
	at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.zza(Unknown Source)
	at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
	at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.n_onCreateView(Native Method)
	at md5270abb39e60627f0f200893b490a1ade.FragmentContainer.onCreateView(FragmentContainer.java:51)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
	at android.view.View.measure(View.java:20158)
	at md5270abb39e60627f0f200893b490a1ade.TabbedPageRenderer.n_onLayout(Native Method)
	at md5270abb39e60627f0f200893b490a1ade.TabbedPageRenderer.onLayout(TabbedPageRenderer.java:71)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:55)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
	at android.view.View.layout(View.java:17945)
	at android.view.ViewGroup.layout(ViewGroup.java:5812)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2716)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1487)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7467)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by deextercz** [comment]
Regarfing the first exception... which version of android do you use?
How often it happens and where?

**Comment by JeanCollas** [comment]
It's reports from Google Play. However it seems the exceptions have changed recently (probably some libraries update, as I haven't changed much logic). Anyway I think I will continue with this project, I wanted to start over something from the official Maps component, it seems this exactly what is done here :)
