### ISSUE TITLE
Deny location on UWP throws exception on UpdateIsShowingUser

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#250]
## BUG / PROBREM REPORT

if you deny location it throws an exception.
Instead of this, it should continue, or there should be some settings to supress exception
### SUMMARY

I am not sure if I am able to handle this exception on my side of app
(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.193
* 

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Deny location on startup

```
Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at iMHD.View.MapPage.<GetUserLocation>d__11.MoveNext()
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll
WinRT information: Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll
WinRT information: Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.
An exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.ni.dll but was not handled in user code
WinRT information: Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.
Additional information: Access is denied.

Your App does not have permission to access location data. Make sure you have defined ID_CAP_LOCATION in the application manifest and that on your phone, you have turned on location by checking Settings > Location.

this occurs at await UpdateIsShowingUser();
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
