### ISSUE TITLE
UWP The object has been closed exception

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#262]
### SUMMARY

When using pin icon from stream The object has been closed exception is thrown
it occurs in BitmapDescriptorExtensions.cs:27 at self.Stream.CopyTo(memoryStream);

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.193

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Just start project with pin from stream 

### ACTUAL IMAGES

```
   at Windows.Storage.Streams.InMemoryRandomAccessStream.ReadAsync(IBuffer buffer, UInt32 count, InputStreamOptions options)
   at System.IO.WinRtToNetFxStreamAdapter.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state, Boolean usedByBlockingWrapper)
   at System.IO.WinRtToNetFxStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at Xamarin.Forms.GoogleMaps.Extensions.UWP.BitmapDescriptorExtensions.ToBitmapDescriptor(BitmapDescriptor self)
   at Xamarin.Forms.GoogleMaps.UWP.PushPin.UpdateIcon(Pin pin)
   at Xamarin.Forms.GoogleMaps.UWP.PushPin..ctor(Pin pin)
   at Xamarin.Forms.GoogleMaps.Logics.UWP.PinLogic.CreateNativeItem(Pin outerItem)
   at Xamarin.Forms.GoogleMaps.Logics.DefaultLogic`3.AddItems(IList newItems)
   at Xamarin.Forms.GoogleMaps.Logics.DefaultLogic`3.RestoreItems()
   at Xamarin.Forms.GoogleMaps.UWP.MapRenderer.<OnElementChanged>d__7.MoveNext()
```

**Comment by JKennedy24** [comment]
Has this issue now been resolved in the pull request that was merged?

**Comment by deextercz** [comment]
I dont think so, but i will investigate that if i have a little time
po 10. 7. 2017 v 15:52 odesílatel JKennedy24 <notifications@github.com>
napsal:
